---
title: "Uwr lectures"
knit: (function(input_file, encoding) { out_dir <- './docs'; rmarkdown::render(input_file,
  encoding=encoding, output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
---

This webpage merge together all projects that were made during summer semester at the Faculty of Mathematics of the University of Wrocław.

### Lectures and associated pages:

#### Advanced linear models [PL]

* [Homework 1 - Logistic regression basics](https://keroiw.github.io/UWR-Lectures/Modele1)
* [Homework 2 - Logistic regression estimates and asymptotics](https://keroiw.github.io/UWR-Lectures/Modele2)
* [Homework 3 - Poisson regression and role of factors in the model](https://keroiw.github.io/UWR-Lectures/Modele3)
* [Homework 4 - Extensions of Poisson regression - overdispersion and zero-inflation](https://keroiw.github.io/UWR-Lectures/Modele4)

#### Big Data [PL/ENG.]

* [Homework 1 - Bonferroni and chi-squared testing procedures](https://keroiw.github.io/UWR-Lectures/BigData1)
* [Homework 2 - Neyman-Pearson test for needle in the haystack problem](https://keroiw.github.io/UWR-Lectures/BigData2)
* [Homework 3 - Multiple testing procedures](https://keroiw.github.io/UWR-Lectures/BigData3)

#### Complex data [ENG.]

* [Homework 1 - The basics of repeated measures](https://keroiw.github.io/UWR-Lectures/ComplexData1)
* [Homework 2 - Likelihood and Wald tests for GLS](https://keroiw.github.io/UWR-Lectures/ComplexData2)
* [Homework 3 - Various types of covariance structure](https://keroiw.github.io/UWR-Lectures/ComplexData3)

#### Methods of classification and dimensionality reduction [ENG.]

* [Project 1 - Introduction to recommender systems](https://keroiw.github.io/UWR-Lectures/RecommenderSystems)


